# Introduction to Pandas
### Level 3 - Challenge with Submission

Make sure you can do the following before moving on. Subit your answer to the instructor team. Calculate **on base percentage** for each player, and return the ordered series of estimates.

$$OBP = \frac{H + BB + HBP}{AB + BB + HBP + SF}$$

In [1]:
import numpy as np
import pandas as pd
from __future__ import print_function
from __future__ import division

In [2]:
baseball = pd.read_csv("../data/baseball.csv", index_col='id')
baseball.head()

,player,year,stint,team,lg,g,ab,r,h,X2b,...,rbi,sb,cs,bb,so,ibb,hbp,sh,sf,gidp
id,,,,,,,,,,,,,,,,,,,,,
88641,womacto01,2006,2,CHN,NL,19,50,6,14,1,...,2.0,1.0,1.0,4,4.0,0.0,0.0,3.0,0.0,0.0
88643,schilcu01,2006,1,BOS,AL,31,2,0,1,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
88645,myersmi01,2006,1,NYA,AL,62,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
88649,helliri01,2006,1,MIL,NL,20,3,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
88650,johnsra05,2006,1,NYA,AL,33,6,0,1,0,...,0.0,0.0,0.0,0,4.0,0.0,0.0,0.0,0.0,0.0

For the equation of OBP, 

$$OBP = \frac{H + BB + HBP}{AB + BB + HBP + SF}$$

If AB + BB + HBP + SF = zero, it will cause error because it cannot divide by zero, so they will be NaN.

In [3]:
def obp(x):
    if x['ab'] + x['bb'] + x['hbp'] + x['sf'] == 0:
        return np.NaN
    else:
        return (x['h'] + x['bb'] + x['hbp'])/(x['ab'] + x['bb'] + x['hbp'] + x['sf'])

In [5]:
baseball['OBP'] = baseball.apply(obp, axis = 1)
baseball[['player','year','OBP']]

          player  year       OBP
id
88641  womacto01  2006  0.333333
88643  schilcu01  2006  0.500000
88645  myersmi01  2006       NaN
88649  helliri01  2006  0.000000
88650  johnsra05  2006  0.166667
88652  finlest01  2006  0.320084
88653  gonzalu01  2006  0.351796
88662   seleaa01  2006  0.222222
89177  francju01  2007  0.311111
89178  francju01  2007  0.327869
89330   zaungr01  2007  0.341026
89333  witasja01  2007       NaN
89334  williwo02  2007  0.101695
89335  wickmbo01  2007       NaN
89336  wickmbo01  2007       NaN
89337  whitero02  2007  0.235294
89338  whiteri01  2007  0.000000
89339  wellsda01  2007  0.266667
89340  wellsda01  2007  0.105263
89341  weathda01  2007       NaN
89343  walketo04  2007  0.288462
89345  wakefti01  2007  0.000000
89347  vizquom01  2007  0.304813
89348  villoro01  2007       NaN
89352  valenjo03  2007  0.302198
89354  trachst01  2007  0.142857
89355  trachst01  2007  0.000000
89359  timlimi01  2007       NaN
89360  thomeji01  2007  0.410448
89361  thomafr04  2007  0.376603
...          ...   ...       ...
89460  guarded01  2007       NaN
89462  griffke02  2007  0.372392
89463  greensh01  2007  0.351738
89464  graffto01  2007  0.315385
89465  gordoto01  2007       NaN
89466  gonzalu01  2007  0.359316
89467  gomezch02  2007  0.277778
89468  gomezch02  2007  0.338889
89469  glavito02  2007  0.285714
89473  floydcl01  2007  0.372671
89474  finlest01  2007  0.245098
89480  embreal01  2007       NaN
89481  edmonji01  2007  0.325183
89482  easleda01  2007  0.357798
89489  delgaca01  2007  0.332784
89493  cormirh01  2007       NaN
89494  coninje01  2007  0.306122
89495  coninje01  2007  0.319502
89497  clemero02  2007  0.500000
89498  claytro01  2007  0.000000
89499  claytro01  2007  0.304348
89501  cirilje01  2007  0.272727
89502  cirilje01  2007  0.327485
89521  bondsba01  2007  0.480084
89523  biggicr01  2007  0.284672
89525  benitar01  2007       NaN
89526  benitar01  2007       NaN
89530  ausmubr01  2007  0.318066
89533   aloumo01  2007  0.391667
89534  alomasa02  2007  0.136364

[100 rows x 3 columns]